param(
    [string]$Instruction
)

Write-Host "Starting Supabase generator..."

# 0. Ensure required folders exist
$folders = @(
    "supabase/tables",
    "supabase/policies",
    "supabase/functions",
    "supabase/triggers",
    "supabase/views"
)

foreach ($folder in $folders) {
    if (-not (Test-Path $folder)) {
        Write-Host "Creating missing folder: $folder"
        New-Item -ItemType Directory -Path $folder | Out-Null
    }
}

# 1. Get instruction (both modes supported)
if (-not $Instruction) {
    $Instruction = Read-Host "Describe what you want to create"
}

# 2. Ask what kind of object this is
Write-Host "What are you creating?"
Write-Host "1) Table"
Write-Host "2) RLS policy"
Write-Host "3) Function"
Write-Host "4) Trigger"
Write-Host "5) View"

$typeChoice = Read-Host "Enter 1-5"

switch ($typeChoice) {
    "1" { $targetFolder = "supabase/tables";   $kind = "table" }
    "2" { $targetFolder = "supabase/policies"; $kind = "policy" }
    "3" { $targetFolder = "supabase/functions";$kind = "function" }
    "4" { $targetFolder = "supabase/triggers"; $kind = "trigger" }
    "5" { $targetFolder = "supabase/views";    $kind = "view" }
    default {
        Write-Host "Invalid choice. Exiting."
        exit
    }
}

# 3. Generate a safe filename
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$fileName = "$timestamp`_$kind.sql"
$filePath = Join-Path $targetFolder $fileName

Write-Host "Creating file: $filePath"

# 4. Create SQL file with natural-language instruction as header
$sqlContent = @"
-- Generated by supabase-generate.ps1
-- Kind: $kind
-- Instruction: $Instruction

-- TODO: Implement SQL for this $kind based on the instruction above.

"@

$sqlContent | Out-File -FilePath $filePath -Encoding UTF8 -Force

# 5. Open in Notepad for review
Write-Host "Opening file in Notepad..."
notepad $filePath

# 6. Run main automation pipeline
Write-Host "Running supabase-auto.ps1..."
./supabase-auto.ps1

Write-Host "Generation and automation complete."
s