-- Generated by supabase-generate.ps1
-- Kind: table
-- Instruction: Create a table for institutions with name, code, email, phone, type, status enum active inactive pending

-- TODO: Implement SQL for this table based on the instruction above.

